import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService {
  static final ValueNotifier<String> activeLanguageNotifier = ValueNotifier<String>('en');

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'dashboard': 'Dashboard',
      'community': 'Community',
      'my_loans': 'My Loans',
      'apply': 'Apply',
      'explore': 'Explore',
      'profile': 'Profile',
      'settings': 'Settings',
      'app_language': 'App Language',
      'logout': 'Logout',
      'refer_earn': 'Refer & Earn',
      'edit_profile': 'Edit Profile',
      'document_vault': 'Document Vault',
      'emi_calculator': 'EMI Calculator',
      'loan_eligibility': 'Loan Eligibility',
      'welcome_back': 'Welcome Back',
      'support_legal': 'SUPPORT & LEGAL',
      'help_center': 'Connect with Support',
      'terms_policy': 'Terms & Privacy Policy',
      'version': 'Version 1.0.4 (Latest Release)',
      'welcome_to': 'Welcome to',
      'active_loans': 'Active Loans',
      'total_amount': 'Total Amount',
      'blogs_insights': 'Blogs & Insights',
      'see_all': 'See All',
      'lending_partners': 'Our Lending Partners',
      'smart_groups': 'Smart Groups',
      'discussions': 'Discussions',
      'create_group': 'Create Group',
      'ai_tools': 'AI Study Tools',
      'account': 'Account',
      'personal_details': 'Personal Details',
      'manage_preferences': 'Manage preferences & account actions',
      'active': 'Active',
      'app_preferences': 'APP PREFERENCES',
      'push_notifications': 'Push Notifications',
      'loan_status_updates': 'Loan status updates & reminders',
      'support_coming_soon': '24/7 Support Portal • Coming Soon',
      'coming_soon': '🔒 Coming Soon',
      'help_center_coming_soon': 'Connect with Support portal is coming soon in the next update!',
      'legal_guidelines': 'Legal guidelines and policies',
      'apply_loan': 'Apply for Loan',
      'application_progress': 'Application Progress',
    },
    'te': {
      'dashboard': 'డ్యాష్‌బోర్డ్',
      'community': 'కమ్యూనిటీ',
      'my_loans': 'నా రుణాలు',
      'apply': 'దరఖాస్తు',
      'explore': 'ఎక్స్‌ప్లోర్',
      'profile': 'ప్రొఫైల్',
      'settings': 'సెట్టింగ్‌లు',
      'app_language': 'యాప్ భాష',
      'logout': 'లాగ్‌అవుట్',
      'refer_earn': 'రెఫర్ & ఎర్న్',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'document_vault': 'డాక్యుమెంట్ వాల్ట్',
      'emi_calculator': 'ఈఎమ్‌ఐ క్యాలిక్యులేటర్',
      'loan_eligibility': 'రుణ అర్హత పరిశీలన',
      'welcome_back': 'స్వాగతం',
      'support_legal': 'సహాయం & నిబంధనలు',
      'help_center': 'సపోర్ట్‌తో కనెక్ట్ అవ్వండి',
      'terms_policy': 'నిబంధనలు & గోప్యతా విధానం',
      'version': 'వెర్షన్ 1.0.4 (తాజా విడుదల)',
      'welcome_to': 'కి స్వాగతం',
      'active_loans': 'యాక్టివ్ రుణాలు',
      'total_amount': 'మొత్తం రుణం',
      'blogs_insights': 'బ్లాగులు & సమాచారం',
      'see_all': 'అన్నీ చూడండి',
      'lending_partners': 'మా రుణ భాగస్వాములు',
      'smart_groups': 'స్మార్ట్ గ్రూప్‌లు',
      'discussions': 'చర్చలు',
      'create_group': 'గ్రూప్ సృష్టించండి',
      'ai_tools': 'AI పరికరాలు',
      'account': 'ఖాతా',
      'personal_details': 'వ్యక్తిగత వివరాలు',
      'manage_preferences': 'ప్రాధాన్యతలు & ఖాతా చర్యలు నిర్వహించు',
      'active': 'యాక్టివ్',
      'app_preferences': 'యాప్ ప్రాధాన్యతలు',
      'push_notifications': 'పుష్ నోటిఫికేషన్లు',
      'loan_status_updates': 'రుణ స్థితి నవీకరణలు & రిమైండర్లు',
      'support_coming_soon': '24/7 మద్దతు పోర్టల్ • త్వరలో వస్తోంది',
      'coming_soon': '🔒 త్వరలో',
      'help_center_coming_soon': 'సపోర్ట్ పోర్టల్ తదుపరి నవీకరణలో అందుబాటులోకి వస్తుంది!',
      'legal_guidelines': 'చట్టపరమైన మార్గదర్శకాలు',
      'apply_loan': 'రుణానికి దరఖాస్తు చేయండి',
      'application_progress': 'దరఖాస్తు పురోగతి',
    },
    'ta': {
      'dashboard': 'டேஷ்போர்டு',
      'community': 'சமூகம்',
      'my_loans': 'என் கடன்கள்',
      'apply': 'விண்ணப்பி',
      'explore': 'ஆராய்க',
      'profile': 'சுயவிவரம்',
      'settings': 'அமைப்புகள்',
      'app_language': 'பயன்பாட்டு மொழி',
      'logout': 'வெளியேறு',
      'refer_earn': 'பரிந்துரைத்து சம்பாதிக்க',
      'edit_profile': 'சுயவிவரத்தை திருத்து',
      'document_vault': 'ஆவண பெட்டகம்',
      'emi_calculator': 'EMI கணக்கிடி',
      'loan_eligibility': 'கடன் தகுதி',
      'welcome_back': 'மீண்டும் வருக',
      'support_legal': 'ஆதரவு & சட்டபூர்வம்',
      'help_center': 'ஆதரவுடன் இணையுங்கள்',
      'terms_policy': 'விதிகள் & தனியுரிமைக் கொள்கை',
      'version': 'பதிப்பு 1.0.4',
      'welcome_to': 'நல்வரவு',
      'active_loans': 'செயலில் உள்ள கடன்கள்',
      'total_amount': 'மொத்த தொகை',
      'blogs_insights': 'வலைப்பதிவுகள்',
      'see_all': 'அனைத்தும் காண்க',
      'lending_partners': 'எங்கள் கடன் பங்காளிகள்',
      'smart_groups': 'ஸ்மார்ட் குழுக்கள்',
      'discussions': 'விவாதங்கள்',
      'create_group': 'குழுவை உருவாக்கு',
      'ai_tools': 'AI கருவிகள்',
      'account': 'கணக்கு',
      'personal_details': 'தனிப்பட்ட விவரங்கள்',
      'manage_preferences': 'விருப்பங்களை & கணக்கு நடவடிக்கைகளை நிர்வகி',
      'active': 'செயல்பாட்டில்',
      'app_preferences': 'பயன்பாட்டு விருப்பங்கள்',
      'push_notifications': 'புஷ் அறிவிப்புகள்',
      'loan_status_updates': 'கடன் நிலை புதுப்பிப்புகள்',
      'support_coming_soon': '24/7 ஆதரவு தொகுப்பு • விரைவில்',
      'coming_soon': '🔒 விரைவில்',
      'help_center_coming_soon': 'ஆதரவு தளம் அடுத்த புதுப்பிப்பில் வரும்!',
      'legal_guidelines': 'சட்ட வழிகாட்டுதல்கள்',
      'apply_loan': 'கடனுக்கு விண்ணப்பி',
      'application_progress': 'விண்ணப்ப முன்னேற்றம்',
    },
    'kn': {
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'community': 'ಕಮ್ಯುನಿಟಿ',
      'my_loans': 'ನನ್ನ ಸಾಲಗಳು',
      'apply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'explore': 'ಅನ್ವೇಷಿಸಿ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'settings': 'ಸಂಯೋಜನೆಗಳು',
      'app_language': 'ಆಪ್ ಭಾಷೆ',
      'logout': 'ಲಾಗ್‌ಔಟ್',
      'refer_earn': 'ರೆಫರ್ & ಗಳಿಸಿ',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      'document_vault': 'ದಾಖಲೆ ಕಣಜ',
      'emi_calculator': 'ಇಎಮ್‌ಐ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'loan_eligibility': 'ಸಾಲದ ಅರ್ಹತೆ',
      'welcome_back': 'ಸುಸ್ವಾಗತ',
      'support_legal': 'ಬೆಂಬಲ & ಕಾನೂನು',
      'help_center': 'ಬೆಂಬಲದೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
      'terms_policy': 'ನಿಯಮಗಳು & ಗೌಪ್ಯತಾ ನೀತಿ',
      'version': 'ಆವೃತ್ತಿ 1.0.4',
      'welcome_to': 'ಸುಸ್ವಾಗತ',
      'active_loans': 'ಸಕ್ರಿಯ ಸಾಲಗಳು',
      'total_amount': 'ಒಟ್ಟು ಮೊತ್ತ',
      'blogs_insights': 'ಬ್ಲಾಗ್‌ಗಳು',
      'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'lending_partners': 'ನಮ್ಮ ಸಾಲದ ಪಾಲುದಾರರು',
      'smart_groups': 'ಸ್ಮಾರ್ಟ್ ಗುಂಪುಗಳು',
      'discussions': 'ಚರ್ಚೆಗಳು',
      'create_group': 'ಗುಂಪು ರಚಿಸಿ',
      'ai_tools': 'AI ಉಪಕರಣಗಳು',
      'account': 'ಖಾತೆ',
      'personal_details': 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
      'manage_preferences': 'ಆದ್ಯತೆಗಳು & ಖಾತೆ ಕ್ರಿಯೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
      'active': 'ಸಕ್ರಿಯ',
      'app_preferences': 'ಆಪ್ ಆದ್ಯತೆಗಳು',
      'push_notifications': 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
      'loan_status_updates': 'ಸಾಲ ಸ್ಥಿತಿ ನವೀಕರಣಗಳು',
      'support_coming_soon': '24/7 ಬೆಂಬಲ ಪೋರ್ಟಲ್ • ಶೀಘ್ರದಲ್ಲಿ',
      'coming_soon': '🔒 ಶೀಘ್ರದಲ್ಲಿ',
      'help_center_coming_soon': 'ಬೆಂಬಲ ಪೋರ್ಟಲ್ ಮುಂದಿನ ನವೀಕರಣದಲ್ಲಿ ಬರಲಿದೆ!',
      'legal_guidelines': 'ಕಾನೂನು ಮಾರ್ಗಸೂಚಿಗಳು',
      'apply_loan': 'ಸಾಲಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'application_progress': 'ಅರ್ಜಿ ಪ್ರಗತಿ',
    },
    'ml': {
      'dashboard': 'ഡാഷ്‌ബോർഡ്',
      'community': 'കമ്മ്യൂണിറ്റി',
      'my_loans': 'എന്റെ വായ്പകൾ',
      'apply': 'അപേക്ഷിക്കുക',
      'explore': 'എക്സ്പ്ലോർ',
      'profile': 'പ്രൊഫൈൽ',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'app_language': 'ആപ്പ് ഭാഷ',
      'logout': 'ലോഗ്ഔട്ട്',
      'refer_earn': 'റെഫർ & സമ്പാദിക്കുക',
      'edit_profile': 'പ്രൊഫൈൽ തിരുത്തുക',
      'document_vault': 'ഡോക്യുമെന്റ് വോൾട്ട്',
      'emi_calculator': 'ഇഎംഐ കാൽക്കുലേറ്റർ',
      'loan_eligibility': 'വായ്പ യോഗ്യത',
      'welcome_back': 'വീണ്ടും സ്വാഗതം',
      'support_legal': 'സഹായം & നിയമപരം',
      'help_center': 'സപ്പോർട്ടുമായി ബന്ധപ്പെടുക',
      'terms_policy': 'വ്യവസ്ഥകളും സ്വകാര്യതാ നയവും',
      'version': 'പതിപ്പ് 1.0.4',
      'welcome_to': 'സ്വാഗതം',
      'active_loans': 'സജീവ വായ്പകൾ',
      'total_amount': 'ആകെ തുക',
      'blogs_insights': 'ബ്ലോഗുകൾ',
      'see_all': 'എല്ലാം കാണുക',
      'lending_partners': 'ഞങ്ങളുടെ വായ്പാ പങ്കാളികൾ',
      'smart_groups': 'സ്മാർട്ട് ഗ്രൂപ്പുകൾ',
      'discussions': 'ചർച്ചകൾ',
      'create_group': 'ഗ്രൂപ്പ് ഉണ്ടാക്കുക',
      'ai_tools': 'AI ഉപകരണങ്ങൾ',
      'account': 'അക്കൗണ്ട്',
      'personal_details': 'വ്യക്തിഗത വിവരങ്ങൾ',
      'manage_preferences': 'മുൻഗണനകളും അക്കൗണ്ട് നടപടികളും കൈകാര്യം ചെയ്യുക',
      'active': 'സജീവം',
      'app_preferences': 'ആപ്പ് മുൻഗണനകൾ',
      'push_notifications': 'പുഷ് അറിയിപ്പുകൾ',
      'loan_status_updates': 'വായ്പ നില അപ്‌ഡേറ്റുകൾ',
      'support_coming_soon': '24/7 പിന്തുണ പോർട്ടൽ • ഉടൻ വരുന്നു',
      'coming_soon': '🔒 ഉടൻ',
      'help_center_coming_soon': 'സപ്പോർട്ട് പോർട്ടൽ അടുത്ത അപ്‌ഡേറ്റിൽ ലഭ്യമാകും!',
      'legal_guidelines': 'നിയമ മാർഗ്ഗനിർദ്ദേശങ്ങൾ',
      'apply_loan': 'വായ്പയ്ക്ക് അപേക്ഷിക്കുക',
      'application_progress': 'അപേക്ഷ പ്രഗതി',
    },
    'hi': {
      'dashboard': 'डैशबोर्ड',
      'community': 'कम्युनिटी',
      'my_loans': 'मेरे ऋण',
      'apply': 'आवेदन',
      'explore': 'एक्सप्लोर',
      'profile': 'प्रोफाइल',
      'settings': 'सेटिंग्स',
      'app_language': 'ऐप भाषा',
      'logout': 'लॉगआउट',
      'refer_earn': 'रेफर और कमाएं',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'document_vault': 'दस्तावेज वॉल्ट',
      'emi_calculator': 'ईएमआई कैलकुलेटर',
      'loan_eligibility': 'ऋण पात्रता',
      'welcome_back': 'स्वागत है',
      'support_legal': 'सहायता और नियम',
      'help_center': 'सपोर्ट से जुड़ें',
      'terms_policy': 'नियम और गोपनीयता नीति',
      'version': 'संस्करण 1.0.4',
      'welcome_to': 'स्वागत है',
      'active_loans': 'सक्रिय ऋण',
      'total_amount': 'कुल राशि',
      'blogs_insights': 'ब्लॉग और विचार',
      'see_all': 'सभी देखें',
      'lending_partners': 'हमारे ऋण भागीदार',
      'smart_groups': 'स्मार्ट ग्रुप्स',
      'discussions': 'चर्चाएं',
      'create_group': 'समूह बनाएं',
      'ai_tools': 'AI अध्ययन उपकरण',
      'account': 'खाता',
      'personal_details': 'व्यक्तिगत विवरण',
      'manage_preferences': 'प्राथमिकताएं और खाता कार्यवाही प्रबंधित करें',
      'active': 'सक्रिय',
      'app_preferences': 'ऐप प्राथमिकताएं',
      'push_notifications': 'पुश नोटिफिकेशन',
      'loan_status_updates': 'ऋण स्थिति अपडेट और अनुस्मारक',
      'support_coming_soon': '24/7 सहायता पोर्टल • जल्द आ रहा है',
      'coming_soon': '🔒 जल्द आ रहा है',
      'help_center_coming_soon': 'सपोर्ट पोर्टल अगले अपडेट में उपलब्ध होगा!',
      'legal_guidelines': 'कानूनी दिशानिर्देश',
      'apply_loan': 'ऋण के लिए आवेदन करें',
      'application_progress': 'आवेदन प्रगति',
    },
  };

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getString('app_language');
    if (saved != null) {
      final code = _nameToCode(saved);
      activeLanguageNotifier.value = code;
    }
  }

  static String _nameToCode(String nameOrDisplayName) {
    if (nameOrDisplayName.contains('Telugu') || nameOrDisplayName.contains('తెలుగు')) return 'te';
    if (nameOrDisplayName.contains('Tamil') || nameOrDisplayName.contains('தமிழ்')) return 'ta';
    if (nameOrDisplayName.contains('Kannada') || nameOrDisplayName.contains('ಕನ್ನಡ')) return 'kn';
    if (nameOrDisplayName.contains('Malayalam') || nameOrDisplayName.contains('മലയാളം')) return 'ml';
    if (nameOrDisplayName.contains('Hindi') || nameOrDisplayName.contains('हिंदी')) return 'hi';
    return 'en';
  }

  static Future<void> setLanguageFromDisplayName(String displayName) async {
    final code = _nameToCode(displayName);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', displayName);
    await prefs.setString('app_language_code', code);
    activeLanguageNotifier.value = code;
  }

  static String tr(String key) {
    final currentCode = activeLanguageNotifier.value;
    final langMap = _translations[currentCode] ?? _translations['en']!;
    return langMap[key] ?? _translations['en']![key] ?? key;
  }

  static String get currentCode => activeLanguageNotifier.value;
}
